version: '3.6'

services:
  web:
    build: ./server
    command: python app.py
    ports:
      - 5000:5000
    env_file: .env

  db:
    build: ./db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    networks:
      - default
    ports:
      - 5432:5432
  
  # ui:
  #   build: ./client